### ISSUE TITLE
Feature Request: Disable Stripes

### ISSUE THREAD

**Issue by jeroenst** [hotNipi/node-red-dashboard-2-ui-gauge-linear#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The bargauges are always deviced by stripes, I would like to set stripes to off so a continuous bar is displayed. Here is an example, based on the old ui level, but the idea is the same:

So from this:

![image](https://github.com/user-attachments/assets/4e18d805-2b4f-41ad-9d71-6dff7026e558)

To this:

![image](https://github.com/user-attachments/assets/82417411-addc-4aa5-a33c-62b0cf82fe1a)

For both horizontal and vertical bars.

**Describe alternatives you've considered**
I tried overriding with CSS but had no good luck

**Additional context**
https://github.com/hotNipi/node-red-contrib-ui-level/issues/49#issuecomment-2427611639

**Comment by hotNipi** [comment]
Even if it may look maybe trivial, it is not. The node is built specially to have segmented bar. It affects everything starting from the configuration page and ends with the layout and functionality. The overall difference is so big that it will make sense to create such widget from scratch.

**Comment by hotNipi** [comment]
Available since v 0.1.0

**Comment by jeroenst** [comment]
Thankyou!
