### ISSUE TITLE
Allow wider range of dim values

### ISSUE THREAD

**Issue by A380Coding** [hotNipi/node-red-dashboard-2-ui-gauge-linear#5]
Dim value can be set between 0.1 to 0.8
Could we get a dim value of 0, so to only show the active part of the gauge? Should be technically feasible?

If yes and while changing, allowing up to 0.9 could be changed as well. Allowing 1 would not make sense for sure, but there might be a use case for 0.9 for some colors?

**Comment by hotNipi** [comment]
0 - 0.9 Since v0.1.5

**Comment by A380Coding** [comment]
thanks
