### ISSUE TITLE
value > max value leads to a too long bar

### ISSUE THREAD

**Issue by A380Coding** [hotNipi/node-red-dashboard-2-ui-gauge-linear#6]
If you set up e.g. min:0 and max:20 but your input is 50 the bar is leaving the widget at the end (kind of an overflow).
If it is the users responsibility to ensure no values larger than max are input you can just close this issue, otherwise a check for input > max or limitation of input value max(input, maxvalue) would avoid this "graphical overflow".

**Comment by hotNipi** [comment]
Is it for any specific OS / Browser cos I don't see any overflow with chrome/firefox.
Show image if you can with dev tools pointing the element with overflow

**Comment by A380Coding** [comment]
Happens with Firefox. And seems to happen only in solid mode, not in segmented.

![image](https://github.com/user-attachments/assets/28a5b349-92ce-452e-bd8b-73bb560433be)

**Comment by hotNipi** [comment]
Strange that it works correctly for me. Anyway I have one improvement to add for this case so maybe I'll do that and then let's try again...

**Comment by hotNipi** [comment]
v0.1.5 has some changes now.

**Comment by A380Coding** [comment]
working thanks!
